import java.util.Map;
import static java.util.Map.entry;

public class Elements {
    public static Map<String, String> elements = Map.ofEntries(
                // Group 1(Alkali metals)
                entry("h", "Hydrogen"),
                entry("li", "Lithium"),
                entry("na", "Sodium"),
                entry("k", "Potassium"),
                entry("rb", "Rubidium"),
                entry("cs", "Caesium"),
                entry("fr", "Francium"),

                // Group 2(Alkali metals)
                entry("be", "Berylium"),
                entry("mg", "Magnesium"),
                entry("ca", "Calcium"),
                entry("sr", "Strontium"),
                entry("ba", "Barium"),
                entry("ra", "Radium"),

                // Group 3(Transition metals)
                entry("sc", "Scandium"),
                entry("y", "Yitrium"),
                entry("lu", "Lutetium"),
                entry("lr", "Lawrencium"),
                entry("ti", "Titanium"),
                entry("zr", "Zirconium"),
                entry("hf", "Halfnium"),
                entry("rf", "Rutherfordium"),
                entry("v", "Vanadium"),
                entry("nb", "Niobium"),
                entry("ta", "Tantalium"),
                entry("db", "Dubnium"),
                entry("cr", "Chromium"),
                entry("mo", "Molundenum"),
                entry("w", "Tungsten"),
                entry("sg", "Seaborgium"),
                entry("mn", "Manganese"),
                entry("tc", "Technetium"),
                entry("re", "Rhenium"),
                entry("bh", "Bohrium"),
                entry("fe", "Iron"),
                entry("ru", "Ruthenium"),
                entry("os", "Osmium"),
                entry("hs", "Hassium"),
                entry("co", "Cobalt"),
                entry("rh", "Rhodium"),
                entry("ir", "Iridium"),
                entry("mt", "Meitnerium"),
                entry("ni", "Nickel"),
                entry("pd", "Palladium"),
                entry("pt", "Platinum"),
                entry("ds", "Darmstadtium"),
                entry("cu", "Copper"),
                entry("ag", "Silver"),
                entry("au", "Gold"),
                entry("rg", "Roentgenium"),
                entry("zn", "Zinc"),
                entry("cd", "Cadmium"),
                entry("hg", "Mercury"),
                entry("cn", "Copernicium"),
                entry("b", "Boron"),
                entry("al", "Aluminium"),
                entry("ga", "Gallium"),
                entry("in", "Indium"),
                entry("tl", "Thallium"),
                entry("nh", "Nihonium"),

                // Group 4
                entry("c", "Carbon"),
                entry("si", "Silicon"),
                entry("ge", "Germanium"),
                entry("sn", "Tin"),
                entry("pb", "Lead"),

                // Group 5
                entry("n", "Nitrogen"),
                entry("p", "Phosphorus"),
                entry("as", "Arsenic"),
                entry("sb", "Antimony"),
                entry("bi", "Bismuth"),

                // Group 6
                entry("o", "Oxygen"),
                entry("s", "Sulfur"),
                entry("se", "Selenium"),
                entry("te", "Tellerium"),
                entry("po", "Polonium"),

                // Group 7(Halogens)
                entry("f", "Fluorine"),
                entry("cl", "Chlorine"),
                entry("br", "Bromine"),
                entry("i", "Iodine"),
                entry("at", "Astatine"),

                // Group 8(Noble gases)
                entry("he", "Helium"),
                entry("ne", "Neon"),
                entry("ar", "Argon"),
                entry("kr", "Krypton"),
                entry("xe", "Xenon"),
                entry("rn", "Radon"),

                // Artificial elements
                entry("fl", "Flerovium"),
                entry("mc", "Moscovium"),
                entry("lv", "Livermorium"),
                entry("ts", "Tennessine"),
                entry("og", "Oganesson"),
                entry("la", "Lanthanium"),
                entry("ac", "Actinium"),
                entry("ce", "Cerium"),
                entry("th", "Thorium"),
                entry("pr", "Praseodymium"),
                entry("pa", "Protactinium"),
                entry("nd", "Neodymium"),
                entry("u", "Uranium"),
                entry("pm", "Promethium"),
                entry("np", "Neptunium"),
                entry("sm", "Samarium"),
                entry("pu", "Plutonium"),
                entry("eu", "Europium"),
                entry("am", "Americium"),
                entry("gd", "Gadolinium"),
                entry("cm", "Curium"),
                entry("tb", "Terbium"),
                entry("bk", "Berkelium"),
                entry("dy", "Dysprosium"),
                entry("cf", "Californium"),
                entry("ho", "Holmium"),
                entry("es", "Einsteinium"),
                entry("er", "Erbium"),
                entry("tm", "Thulium"),
                entry("md", "Mendelevium"),
                entry("yb", "Ytterbium"),
                entry("no", "Nobelium")
            );
}
